name: build

on:
  push:
    branches: [ main ]
    tags:        
      - '*'
    paths-ignore:
      - '.github/workflows/**'
      - '!.github/workflows/build.yaml'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '.github/workflows/**'
      - '!.github/workflows/build.yaml'

jobs:
  e2e-tests-testing-farm:
    name: Run All E2E tests on Testing Farm CI 
    runs-on: ubuntu-24.04
    permissions:
      checks: write # required for mikepenz/action-junit-report
    steps: 
      - name: PR check tests on Testing Farm 
        uses: sclorg/testing-farm-as-github-action@v4
        with:
          api_key: ${{ secrets.TF_TOKEN }}
          compose: Fedora-42
          tmt_plan_filter: 'name:plans/pd-e2e-plan/e2e-smoke'
        